module.exports = {
  theme: {
    screens: {},
    colors: {
      primary: '#ff6600',
      primarySoft: '#33231d',
      secondary: '#292929',
      dark: '#121212',
      accent: '#ff6600',
      error: '#ff0000',
      warning: '#ff9800',
      info: '#2196f3',
      success: '#4caf50',
      white: '#ffffff',
      black: '#000000',
      grey: '#d9d9d9',
      softGrey: '#f9f9f9',
      darkGrey: '#6e6e6e',
    },
    fontFamily: {
      montserrat: ['Montserrat-Regular'],
      montserratMedium: ['Montserrat-Medium'],
      montserratSemiBold: ['Montserrat-SemiBold'],
      montserratBold: ['Montserrat-Bold'],
      montserratExtraBold: ['Montserrat-ExtraBold'],
      montserratLight: ['Montserrat-Light'],
      montserratExtraLight: ['Montserrat-ExtraLight'],
      montserratThin: ['Montserrat-Thin'],
    },
    extend: {},
  },
};
